apiVersion: v1
version: 0.0.1
appVersion: latest
name: goquorum-enhanced-permission
description: Quorum Enhanced Permission deploy with Helm chart in Kubernetes
keywords:
  - ethereum
  - quorum
  - enterprise
  - blockchain
  - pegasys
  - consensys
home: https://consensys.net/quorum/
sources:
  - https://consensys.net/quorum/
maintainers:
  - name: Toan Le
    email: toanledev@gmail.com

