---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lc.name" . }}-sa
  namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "lc.name" . }}-role
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "lc.name" . }}
    helm.sh/chart: {{ include "lc.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["create", "get", "list", "update", "delete" ]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch" ]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "lc.name" . }}-rb
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "lc.name" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ include "lc.name" . }}-sa
    namespace: {{ .Release.Namespace }}


---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "lc.name" . }}-init
  labels:
    app: {{ template "lc.name" . }}
    chart: {{ template "lc.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    namespace: {{ .Release.Namespace }}
    app.kubernetes.io/name: {{ include "lc.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "lc.chart" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook-delete-policy: "hook-succeeded"
spec:
  backoffLimit: 3
  completions: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "lc.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "lc.name" . }}-sa
      restartPolicy: "Never"
      containers:
        - name: generate-enhanced-permission
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          securityContext:
            runAsUser: 0
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: RPC_URL
            value: "{{ .Values.deployer.rpcUrl }}"
          - name: NETWORK_ID
            valueFrom:
              configMapKeyRef:
                name: goquorum-networkid
                key: networkId
          - name: ACCOUNT_PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                name: "{{ .Values.deployer.nodeSecretKeyName }}"
                key: accountPrivate.key
          command:
            - /bin/bash
            - -c
          args:
            - |