---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "subgraph.fullname" . }}
  labels:
    app: {{ template "subgraph.fullname" . }}
    chart: {{ template "subgraph.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    namespace: {{ .Release.Namespace }}docker
    app.kubernetes.io/name: {{ include "subgraph.fullname" . }}
    helm.sh/chart: {{ include "subgraph.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ template "subgraph.fullname" . }}
    release: {{ .Release.Name }}
    component: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "subgraph.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http-graphql
      port: 8000
      targetPort: http-graphql
      protocol: TCP
    - name: ws-graphql
      port: 8001
      targetPort: ws-graphql
      protocol: TCP
    - name: json-rpc-admin
      port: 8020
      targetPort: json-rpc-admin
      protocol: TCP
    - name: indexer
      port: 8030
      targetPort: indexer
      protocol: TCP
    - name: metrics
      port: 8040
      targetPort: metrics
      protocol: TCP

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: {{ include "lc.fullname" . }}
#   labels:
#     app: {{ template "lc.fullname" . }}
#     chart: {{ template "lc.chart" . }}
#     release: {{ .Release.Name }}
#     heritage: {{ .Release.Service }}
#     namespace: {{ .Release.Namespace }}
#     app.kubernetes.io/name: {{ include "lc.fullname" . }}
#     helm.sh/chart: {{ include "lc.chart" . }}
#     app.kubernetes.io/instance: {{ .Release.Name }}
#     app.kubernetes.io/managed-by: {{ .Release.Service }}
#   namespace: {{ .Release.Namespace }}
# spec:
#   type: ClusterIP
#   selector:
#     app: {{ template "lc.fullname" . }}
#     release: {{ .Release.Name }}
#     component: {{ .Release.Name }}
#     app.kubernetes.io/name: {{ include "lc.fullname" . }}
#     app.kubernetes.io/instance: {{ .Release.Name }}
#   ports:
#     - name: server
#       port: 3000
#       targetPort: server
#       protocol: TCP