image:
  explorer:
    repository: consensys/quorum-explorer
    tag: e175e0b
    pullPolicy: Always #IfNotPresent

resources:
  requests:
    cpu: 1000m
    memory: 1G

# This contains the quorum-dev-quickstart test accounts but can be changed to the generated member accounts or your own choice
explorerConfig: |
  {
  "algorithm": "qbft",
  "nodes": [{
      "name": "validator1",
      "client": "goquorum",
      "rpcUrl": "http://goquorum-node-validator-1.quorum.svc.cluster.local:8545",
      "privateTxUrl": ""
    },
    {
      "name": "validator2",
      "client": "goquorum",
      "rpcUrl": "http://goquorum-node-validator-2.quorum.svc.cluster.local:8545",
      "privateTxUrl": ""
    },
    {
      "name": "validator3",
      "client": "goquorum",
      "rpcUrl": "http://goquorum-node-validator-3.quorum.svc.cluster.local:8545",
      "privateTxUrl": ""
    },
    {
      "name": "validator4",
      "client": "goquorum",
      "rpcUrl": "http://goquorum-node-validator-4.quorum.svc.cluster.local:8545",
      "privateTxUrl": ""
    },
    {
      "name": "validator5",
      "client": "goquorum",
      "rpcUrl": "http://goquorum-node-validator-5.quorum.svc.cluster.local:8545",
      "privateTxUrl": ""
    },
    {
      "name": "validator6",
      "client": "goquorum",
      "rpcUrl": "http://goquorum-node-validator-6.quorum.svc.cluster.local:8545",
      "privateTxUrl": ""
    },
    {
      "name": "validator7",
      "client": "goquorum",
      "rpcUrl": "http://goquorum-node-validator-7.quorum.svc.cluster.local:8545",
      "privateTxUrl": ""
    },
    {
      "name": "member1",
      "client": "goquorum",
      "rpcUrl": "http://goquorum-node-member-1.quorum.svc.cluster.local:8545",
      "privateTxUrl": "http://goquorum-node-member-1.quorum.svc.cluster.local:9080",
      "privateKey": "0x8f2a55949038a9610f50fb23b5883af3b4ecb3c3bb792cbcefbd1542c692be63",
      "accountAddress": "0xfe3b557e8fb62b89f4916b721be55ceb828dbd73"
    }
  ]
  }

explorerEnvConfig: |-
  QE_BASEPATH="/explorer"
  QE_CONFIG_PATH="/app/config.json"
  NODE_ENV=production

  DISABLE_AUTH=true

  NEXTAUTH_URL=http://localhost:25000
  NEXTAUTH_URL_INTERNAL=http://localhost:25000
  NEXTAUTH_SECRET=
  # To generate NEXTAUTH_SECRET: `openssl rand -hex 32` or go to https://generate-secret.now.sh/32

  local_username=
  local_password=

  GITHUB_ID=
  GITHUB_SECRET=

  AUTH0_ID=
  AUTH0_SECRET=
  AUTH0_DOMAIN=

  FACEBOOK_ID=
  FACEBOOK_SECRET=

  GOOGLE_ID=
  GOOGLE_SECRET=

  TWITTER_ID=
  TWITTER_SECRET=

  GITLAB_CLIENT_ID=
  GITLAB_CLIENT_SECRET=

  AZURE_AD_CLIENT_ID=
  AZURE_AD_CLIENT_SECRET=
  AZURE_AD_TENANT_ID=

  ATLASSIAN_CLIENT_ID=
  ATLASSIAN_CLIENT_SECRET=

  COGNITO_CLIENT_ID=
  COGNITO_CLIENT_SECRET=
  COGNITO_ISSUER=

  OKTA_CLIENT_ID=
  OKTA_CLIENT_SECRET=
  OKTA_ISSUER=

  SLACK_CLIENT_ID=
  SLACK_CLIENT_SECRET=